import {
  Company,
  Contact,
  Lead,
  Deal,
  Project,
  Task,
  Employee,
  Department,
  AttendanceRecord,
  LeaveRequest,
  Candidate,
  JobPosition,
  Expense,
  Asset,
  DocumentItem,
  NoteItem,
  ActivityItem,
  AuditLogItem,
  AutomationRule,
  SystemSettings,
  User,
  Milestone,
  UserInvitation,
} from "../types";

export const initialUsers: User[] = [
  {
    id: "usr-01",
    name: "Alex Vance",
    email: "alex.vance@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "Admin",
    department: "Executive Management",
    jobTitle: "Chief Operations Officer",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-02",
    name: "Priya Sharma",
    email: "priya.sharma@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    role: "HR Manager",
    department: "Human Resources",
    jobTitle: "Head of People & Culture",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-03",
    name: "Marcus Reed",
    email: "marcus.reed@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    role: "Sales Manager",
    department: "Sales & Revenue",
    jobTitle: "Director of Enterprise Sales",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-04",
    name: "Elena Rostova",
    email: "elena.rostova@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    role: "Project Manager",
    department: "Engineering",
    jobTitle: "Principal Technical Program Manager",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-05",
    name: "Vikram Patel",
    email: "vikram.patel@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    role: "Employee",
    department: "Engineering",
    jobTitle: "Lead Full Stack Engineer",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-01",
    name: "Yenduri Hima Sai Sri",
    email: "Yhima17@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Yenduri+Hima+Sai+Sri&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "QA | DM",
    jobTitle: "QA | DM",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-02",
    name: "Dupuguntla Phani Kumar",
    email: "Dphan18@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Dupuguntla+Phani+Kumar&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "SDE",
    jobTitle: "SDE",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-03",
    name: "Mutchi Jyothi",
    email: "Mjyot19@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Mutchi+Jyothi&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "SDE-FE",
    jobTitle: "SDE-FE",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-04",
    name: "Koraganji Lavanya",
    email: "Klava20@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Koraganji+Lavanya&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "SDE-FE | DM",
    jobTitle: "SDE-FE | DM",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-05",
    name: "Gollapalli Bhanu Prasad",
    email: "Gbhan21@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Gollapalli+Bhanu+Prasad&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "SDE",
    jobTitle: "SDE",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-06",
    name: "Paila Ganesh",
    email: "Pgane22@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Paila+Ganesh&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "BA",
    jobTitle: "BA",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-07",
    name: "Koduru Dinesh Sree Sai Bhagavan Krishna",
    email: "Kdine23@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Koduru+Dinesh&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "SDE",
    jobTitle: "SDE",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-08",
    name: "PATHAN MUSTAQ ALIKHAN",
    email: "pmust24@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Pathan+Mustaq+Alikhan&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "QA | DM",
    jobTitle: "QA | DM",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-09",
    name: "Siram Anusha",
    email: "sanus25@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Siram+Anusha&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "SDE-FE",
    jobTitle: "SDE-FE",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-soxit-10",
    name: "Kancharla Sai Vivek",
    email: "ksaiv26@soxit.org",
    avatar: "https://ui-avatars.com/api/?name=Kancharla+Sai+Vivek&background=2563eb&color=fff&bold=true",
    role: "Employee",
    department: "SDE",
    jobTitle: "SDE",
    organizationId: "org-worqester-01",
  },
];

export const initialSettings: SystemSettings = {
  companyName: "Worqester Technologies",
  tagline: "Manage Customers. People. Projects. Growth.",
  currency: "INR",
  currencySymbol: "₹",
  timezone: "Asia/Kolkata (IST, UTC+5:30)",
  theme: "dark",
  enabledModules: {
    crm: true,
    projects: true,
    tasks: true,
    hrm: true,
    recruitment: true,
    attendance: true,
    expenses: true,
    assets: true,
    documents: true,
    reports: true,
    ai: true,
    automations: true,
  },
  modulesEnabled: {
    crm: true,
    projects: true,
    tasks: true,
    hrm: true,
    recruitment: true,
    attendance: true,
    expenses: true,
    assets: true,
    documents: true,
    reports: true,
    ai: true,
    automations: true,
  },
};

export const initialCompanies: Company[] = [];

export const initialContacts: Contact[] = [];

export const initialLeads: Lead[] = [];

export const initialDeals: Deal[] = [];

export const initialProjects: Project[] = [];

export const initialTasks: Task[] = [];

export const initialDepartments: Department[] = [
  {
    id: "dept-01",
    name: "Engineering & Cloud",
    headName: "Unassigned",
    headEmail: "",
    location: "Headquarters",
    budget: 0,
    employeeCount: 10,
    description: "Core cloud infrastructure, backend APIs, frontend client systems, and DevOps.",
  },
  {
    id: "dept-02",
    name: "Sales & Strategic Partnerships",
    headName: "Unassigned",
    headEmail: "",
    location: "Headquarters",
    budget: 0,
    employeeCount: 0,
    description: "Enterprise accounts, outbound expansion, solution architecture, and customer pipeline.",
  },
  {
    id: "dept-03",
    name: "Human Resources & Talent",
    headName: "Unassigned",
    headEmail: "",
    location: "Headquarters",
    budget: 0,
    employeeCount: 0,
    description: "Talent acquisition, employee experience, compensation & benefits, and compliance.",
  },
  {
    id: "dept-04",
    name: "Product & UX Design",
    headName: "Unassigned",
    headEmail: "",
    location: "Headquarters",
    budget: 0,
    employeeCount: 0,
    description: "Product roadmap, user research, interaction design, and design systems.",
  },
  {
    id: "dept-05",
    name: "Finance & Operations",
    headName: "Unassigned",
    headEmail: "",
    location: "Headquarters",
    budget: 0,
    employeeCount: 0,
    description: "Financial governance, budgeting, audit, billing, and organizational operations.",
  },
];

export const initialEmployees: Employee[] = [
  {
    id: "emp-soxit-01",
    organizationId: "org-worqester-01",
    eId: "o170917",
    employeeNumber: "o170917",
    firstName: "Yenduri",
    lastName: "Hima Sai Sri",
    fullName: "Yenduri Hima Sai Sri",
    workEmail: "Yhima17@soxit.org",
    email: "Yhima17@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00001",
    avatar: "https://ui-avatars.com/api/?name=Yenduri+Hima+Sai+Sri&background=2563eb&color=fff&bold=true",
    department: "QA | DM",
    team: "QA | DM",
    designation: "QA | DM",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["QA", "DM"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-02",
    organizationId: "org-worqester-01",
    eId: "o170918",
    employeeNumber: "o170918",
    firstName: "Dupuguntla",
    lastName: "Phani Kumar",
    fullName: "Dupuguntla Phani Kumar",
    workEmail: "Dphan18@soxit.org",
    email: "Dphan18@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00002",
    avatar: "https://ui-avatars.com/api/?name=Dupuguntla+Phani+Kumar&background=2563eb&color=fff&bold=true",
    department: "SDE",
    team: "SDE",
    designation: "SDE",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["SDE"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-03",
    organizationId: "org-worqester-01",
    eId: "o170919",
    employeeNumber: "o170919",
    firstName: "Mutchi",
    lastName: "Jyothi",
    fullName: "Mutchi Jyothi",
    workEmail: "Mjyot19@soxit.org",
    email: "Mjyot19@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00003",
    avatar: "https://ui-avatars.com/api/?name=Mutchi+Jyothi&background=2563eb&color=fff&bold=true",
    department: "SDE-FE",
    team: "SDE-FE",
    designation: "SDE-FE",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["SDE-FE"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-04",
    organizationId: "org-worqester-01",
    eId: "o170920",
    employeeNumber: "o170920",
    firstName: "Koraganji",
    lastName: "Lavanya",
    fullName: "Koraganji Lavanya",
    workEmail: "Klava20@soxit.org",
    email: "Klava20@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00004",
    avatar: "https://ui-avatars.com/api/?name=Koraganji+Lavanya&background=2563eb&color=fff&bold=true",
    department: "SDE-FE | DM",
    team: "SDE-FE | DM",
    designation: "SDE-FE | DM",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["SDE-FE", "DM"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-05",
    organizationId: "org-worqester-01",
    eId: "o170821",
    employeeNumber: "o170821",
    firstName: "Gollapalli",
    lastName: "Bhanu Prasad",
    fullName: "Gollapalli Bhanu Prasad",
    workEmail: "Gbhan21@soxit.org",
    email: "Gbhan21@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00005",
    avatar: "https://ui-avatars.com/api/?name=Gollapalli+Bhanu+Prasad&background=2563eb&color=fff&bold=true",
    department: "SDE",
    team: "SDE",
    designation: "SDE",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["SDE"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-06",
    organizationId: "org-worqester-01",
    eId: "o170922",
    employeeNumber: "o170922",
    firstName: "Paila",
    lastName: "Ganesh",
    fullName: "Paila Ganesh",
    workEmail: "Pgane22@soxit.org",
    email: "Pgane22@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00006",
    avatar: "https://ui-avatars.com/api/?name=Paila+Ganesh&background=2563eb&color=fff&bold=true",
    department: "BA",
    team: "BA",
    designation: "BA",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["BA"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-07",
    organizationId: "org-worqester-01",
    eId: "o170923",
    employeeNumber: "o170923",
    firstName: "Koduru",
    lastName: "Dinesh Sree Sai Bhagavan Krishna",
    fullName: "Koduru Dinesh Sree Sai Bhagavan Krishna",
    workEmail: "Kdine23@soxit.org",
    email: "Kdine23@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00007",
    avatar: "https://ui-avatars.com/api/?name=Koduru+Dinesh&background=2563eb&color=fff&bold=true",
    department: "SDE",
    team: "SDE",
    designation: "SDE",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["SDE"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-08",
    organizationId: "org-worqester-01",
    eId: "o170924",
    employeeNumber: "o170924",
    firstName: "PATHAN",
    lastName: "MUSTAQ ALIKHAN",
    fullName: "PATHAN MUSTAQ ALIKHAN",
    workEmail: "pmust24@soxit.org",
    email: "pmust24@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00008",
    avatar: "https://ui-avatars.com/api/?name=Pathan+Mustaq+Alikhan&background=2563eb&color=fff&bold=true",
    department: "QA | DM",
    team: "QA | DM",
    designation: "QA | DM",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["QA", "DM"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-09",
    organizationId: "org-worqester-01",
    eId: "o170925",
    employeeNumber: "o170925",
    firstName: "Siram",
    lastName: "Anusha",
    fullName: "Siram Anusha",
    workEmail: "sanus25@soxit.org",
    email: "sanus25@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00009",
    avatar: "https://ui-avatars.com/api/?name=Siram+Anusha&background=2563eb&color=fff&bold=true",
    department: "SDE-FE",
    team: "SDE-FE",
    designation: "SDE-FE",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["SDE-FE"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
  {
    id: "emp-soxit-10",
    organizationId: "org-worqester-01",
    eId: "o170926",
    employeeNumber: "o170926",
    firstName: "Kancharla",
    lastName: "Sai Vivek",
    fullName: "Kancharla Sai Vivek",
    workEmail: "ksaiv26@soxit.org",
    email: "ksaiv26@soxit.org",
    personalEmail: "",
    phone: "+91 98000 00010",
    avatar: "https://ui-avatars.com/api/?name=Kancharla+Sai+Vivek&background=2563eb&color=fff&bold=true",
    department: "SDE",
    team: "SDE",
    designation: "SDE",
    location: "Headquarters",
    employmentType: "Full Time",
    joiningDate: "2026-09-29",
    status: "Active",
    workMode: "On-site",
    skills: ["SDE"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 0,
    leaveBalanceDays: 18,
    salaryBasic: 0,
    bankAccountMasked: "Bank **** 0000",
  },
];

export const initialAttendance: AttendanceRecord[] = [];

export const initialLeaveRequests: LeaveRequest[] = [];

export const initialJobPositions: JobPosition[] = [];

export const initialCandidates: Candidate[] = [];

export const initialExpenses: Expense[] = [];

export const initialAssets: Asset[] = [];

export const initialDocuments: DocumentItem[] = [];

export const initialNotes: NoteItem[] = [];

export const initialActivities: ActivityItem[] = [];

export const initialAuditLogs: AuditLogItem[] = [];

export const initialAutomations: AutomationRule[] = [];

export const initialMilestones: Milestone[] = [];

export const initialInvitations: UserInvitation[] = [];
